language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

# Scripts to be run such as tests
script:
  - docker build udagram-api-user -t udfeed:latest
  - docker build udagram-api-feed -t vdj4y/udagram:uduser-latest


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vdj4y/udagram:uduser-latest
